#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
    typeit=1
    shift
fi

WAYLAND_MENUS=("dmenu-wl" "fuzzel" "rofi" "wofi")
X11_MENUS=("dmenu" "rofi")
menus=()
dmenu=()

if [[ -n $WAYLAND_DISPLAY ]]; then
    menus=("${WAYLAND_MENUS[@]}")
    xdotool="ydotool type --file -"
elif [[ -n $DISPLAY ]]; then
    menus=("${X11_MENUS[@]}")
    xdotool="xdotool type --clearmodifiers --file -"
else
    echo "Error: No Wayland or X11 display detected" >&2
    exit 1
fi

for menu in "${menus[@]}"; do
    if [[ -n $(command -v $menu) ]]; then
        case "$menu" in
            "dmenu") dmenu=("dmenu") ;;
            "dmenu-wl") dmenu=("dmenu-wl") ;;
            "fuzzel") dmenu=("fuzzel" "-d") ;;
            "rofi") dmenu=("rofi" "-dmenu") ;;
            "wofi") dmenu=("wofi" "-d") ;;
        esac
        break
    fi
done

if [[ -z $dmenu ]]; then
    echo "No dmenu-compatible program found. Install one of:" >&2
    echo "${menus[*]}" >&2
    exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | "${dmenu[@]}" "$@")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
    pass show -c "$password" 2>/dev/null
else
    pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
fi

notify=""

if [[ -n $(command -v notify-send) ]]; then
    notify="notify-send"
elif [[ -n $(command -v dunstify) ]]; then
    notify="dunstify"
fi

if [[ -n $notify ]]; then
    $notify -a "fuzzypass" "Copied $password to clipboard" "Will clear in 45 seconds" -t 2500
fi
